/**
 * Comprehensive predefined presets for examinations, recruitment tests, ID cards, and passports.
 * Includes dimensions, recommended KB limits, and category tags.
 */

export const PRESET_CATEGORIES = [
  { id: 'all', label: 'All Presets' },
  { id: 'gov_exam', label: 'Govt. Examinations' },
  { id: 'passport_id', label: 'Passport & Visa' },
  { id: 'banking', label: 'Banking & Finance' },
  { id: 'university', label: 'University / Entrance' },
  { id: 'social', label: 'Social & Web' },
];

export const PRESET_OPTIONS = [
  {
    id: 'ssc-cgl-photo',
    name: 'SSC CGL / CHSL / MTS Photo',
    category: 'gov_exam',
    badge: 'Popular Exam',
    width: 200,
    height: 230,
    targetKb: 50,
    minKb: 20,
    maxKb: 50,
    format: 'image/jpeg',
    aspectLabel: '200 × 230 px',
    description: 'Commonly specified dimension for Staff Selection Commission online application forms.',
    instructions: 'Light background, clear front face view. Standard file size 20 KB to 50 KB.',
  },
  {
    id: 'ssc-signature',
    name: 'SSC Official Signature',
    category: 'gov_exam',
    badge: 'Signature',
    width: 140,
    height: 60,
    targetKb: 20,
    minKb: 10,
    maxKb: 20,
    format: 'image/jpeg',
    aspectLabel: '140 × 60 px',
    description: 'Signature requirement for SSC recruitment portal.',
    instructions: 'Black/blue ink on white paper, cropped without shadows. Size 10 KB to 20 KB.',
  },
  {
    id: 'upsc-cse-photo',
    name: 'UPSC Civil Services / NDA / CDS',
    category: 'gov_exam',
    badge: 'UPSC OTR',
    width: 350,
    height: 350,
    targetKb: 100,
    minKb: 20,
    maxKb: 300,
    format: 'image/jpeg',
    aspectLabel: '350 × 350 px (1:1)',
    description: 'Standard square format photo for UPSC One Time Registration (OTR).',
    instructions: 'Name and date of photograph as required by latest UPSC notification.',
  },
  {
    id: 'ibps-sbi-photo',
    name: 'IBPS / SBI Bank PO & Clerk Photo',
    category: 'banking',
    badge: 'Banking',
    width: 200,
    height: 230,
    targetKb: 50,
    minKb: 20,
    maxKb: 50,
    format: 'image/jpeg',
    aspectLabel: '200 × 230 px (4.5 × 3.5 cm)',
    description: 'Institute of Banking Personnel Selection applicant photograph.',
    instructions: 'White or light background. Standard limit 20 KB to 50 KB.',
  },
  {
    id: 'ibps-signature',
    name: 'IBPS / Bank Form Signature',
    category: 'banking',
    badge: 'Banking',
    width: 140,
    height: 60,
    targetKb: 20,
    minKb: 10,
    maxKb: 20,
    format: 'image/jpeg',
    aspectLabel: '140 × 60 px',
    description: 'Signature upload for IBPS/SBI banking online applications.',
    instructions: 'Sign on white paper with black ink. Standard limit 10 KB to 20 KB.',
  },
  {
    id: 'rrb-railway-photo',
    name: 'RRB Railway Recruitment Photo',
    category: 'gov_exam',
    badge: 'Railways',
    width: 240,
    height: 320,
    targetKb: 70,
    minKb: 30,
    maxKb: 70,
    format: 'image/jpeg',
    aspectLabel: '240 × 320 px (3:4)',
    description: 'Indian Railways RRB ALP, Group D & NTPC application photo.',
    instructions: 'Color passport photograph with plain white background.',
  },
  {
    id: 'passport-standard-in',
    name: 'Standard Indian Passport Photo',
    category: 'passport_id',
    badge: '3.5 × 4.5 cm',
    width: 413,
    height: 531,
    targetKb: 100,
    minKb: 40,
    maxKb: 200,
    format: 'image/jpeg',
    aspectLabel: '413 × 531 px (3.5 × 4.5 cm)',
    description: 'Equivalent to 3.5 cm × 4.5 cm at 300 DPI for Seva Kendra & Visa.',
    instructions: '80% face coverage, neutral expression, white backdrop.',
  },
  {
    id: 'passport-us-visa',
    name: 'US Visa / Green Card (2 × 2 inch)',
    category: 'passport_id',
    badge: '2 × 2 inch',
    width: 600,
    height: 600,
    targetKb: 240,
    minKb: 100,
    maxKb: 240,
    format: 'image/jpeg',
    aspectLabel: '600 × 600 px (1:1)',
    description: 'Standard 2x2 inches (51x51 mm) square format for US DS-160.',
    instructions: 'White or off-white background, head centered between 50% and 69% of height.',
  },
  {
    id: 'nta-neet-jee-photo',
    name: 'NTA NEET / JEE Main / CUET',
    category: 'university',
    badge: 'NTA Entrance',
    width: 300,
    height: 400,
    targetKb: 150,
    minKb: 10,
    maxKb: 200,
    format: 'image/jpeg',
    aspectLabel: '300 × 400 px',
    description: 'National Testing Agency applicant photograph format.',
    instructions: 'White background, 80% face coverage with ears visible.',
  },
  {
    id: 'gate-exam-photo',
    name: 'GATE Exam Applicant Photo',
    category: 'university',
    badge: 'GATE',
    width: 480,
    height: 640,
    targetKb: 200,
    minKb: 50,
    maxKb: 200,
    format: 'image/jpeg',
    aspectLabel: '480 × 640 px',
    description: 'Graduate Aptitude Test in Engineering standard photo.',
    instructions: 'Good resolution, white background, no cap or dark glasses.',
  },
  {
    id: 'square-avatar-web',
    name: 'Square Profile / Social Avatar',
    category: 'social',
    badge: 'Social / Web',
    width: 500,
    height: 500,
    targetKb: 100,
    minKb: 20,
    maxKb: 150,
    format: 'image/jpeg',
    aspectLabel: '500 × 500 px (1:1)',
    description: 'Clean square photo for LinkedIn, GitHub, or online portfolios.',
    instructions: 'Professional headshot, crisp avatar size.',
  },
];
